### ISSUE TITLE
Change inputs task from UpperCamelCase to lowerCamelCase

### ISSUE THREAD

**Issue by carlosgit2016** [carlosgit2016/nodejs-runner#13]
To improve the task standard with others and improve visualization when created in yaml, change the properties inside task.json as below.

**Before**
```yaml
- task: NodeJSRunner@0
  inputs:
    Arguments: 
    InlineScript: 
    ScriptPath: 
    ScriptSource: Inline | FilePath
    WorkingDirectory: 
```
**After**
```yaml
- task: NodeJSRunner@0
  inputs:
    arguments: 
    inlineScript: 
    scriptPath: 
    scriptSource: inline | filePath
    workingDirectory: 
```
